// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace WDPR.Migrations
{
    [DbContext(typeof(MyContext))]
    [Migration("20220119183629_1")]
    partial class _1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("WDPR.Models.Hulpverlener", b =>
                {
                    b.Property<int>("Hulpverlenerid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("Gebruikersnaam")
                        .HasColumnType("TEXT");

                    b.Property<string>("HoeHelpen")
                        .HasColumnType("TEXT");

                    b.Property<string>("MijnSTudie")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProfielFoto")
                        .HasColumnType("TEXT");

                    b.Property<string>("Specialisme")
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefoonnummer")
                        .HasColumnType("TEXT");

                    b.Property<string>("VoorNaam")
                        .HasColumnType("TEXT");

                    b.Property<string>("WatAls")
                        .HasColumnType("TEXT");

                    b.Property<string>("WiebenIk")
                        .HasColumnType("TEXT");

                    b.Property<string>("achterNaam")
                        .HasColumnType("TEXT");

                    b.HasKey("Hulpverlenerid");

                    b.ToTable("Hulpverlener");
                });
#pragma warning restore 612, 618
        }
    }
}
